// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Switchly.WebApi.Context;

#nullable disable

namespace Switchly.WebApi.Context.Migrations
{
    [DbContext(typeof(SwitchlyDbContext))]
    [Migration("20260906102527_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultRolloutKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DefaultRolloutPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEnvironmentId");

                    b.HasIndex("FeatureFlagId", "ProjectEnvironmentId")
                        .IsUnique();

                    b.ToTable("FeatureFlagEnvironments", t =>
                        {
                            t.HasCheckConstraint("CK_FeatureFlagEnvironment_DefaultRolloutPercentage", "\"DefaultRolloutPercentage\" >= 0 AND \"DefaultRolloutPercentage\" <= 100");
                        });
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlagSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureFlagEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("SegmentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SegmentGroupId");

                    b.HasIndex("FeatureFlagEnvironmentId", "Priority");

                    b.HasIndex("FeatureFlagEnvironmentId", "SegmentGroupId")
                        .IsUnique();

                    b.ToTable("FeatureFlagSegments");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FlagsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("FlagsProjects");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("ProjectEnvironments");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.SegmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogicalOperator")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("SegmentGroups");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.SegmentRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SegmentGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TraitKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentGroupId", "SortOrder");

                    b.ToTable("SegmentRules");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlag", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.FlagsProject", "FlagsProject")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlagsProject");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.FeatureFlag", "FeatureFlag")
                        .WithMany("FeatureFlagEnvironments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly.WebApi.Entities.ProjectEnvironment", "ProjectEnvironment")
                        .WithMany("FeatureFlagEnvironments")
                        .HasForeignKey("ProjectEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");

                    b.Navigation("ProjectEnvironment");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlagSegment", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany("FeatureFlagSegments")
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly.WebApi.Entities.SegmentGroup", "SegmentGroup")
                        .WithMany("FeatureFlagSegments")
                        .HasForeignKey("SegmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagEnvironment");

                    b.Navigation("SegmentGroup");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FlagsProject", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.OrganizationMember", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Switchly.WebApi.Entities.User", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.FlagsProject", "FlagsProject")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlagsProject");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.SegmentGroup", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.Organization", "Organization")
                        .WithMany("SegmentGroups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.SegmentRule", b =>
                {
                    b.HasOne("Switchly.WebApi.Entities.SegmentGroup", "SegmentGroup")
                        .WithMany("Rules")
                        .HasForeignKey("SegmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentGroup");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlag", b =>
                {
                    b.Navigation("FeatureFlagEnvironments");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FeatureFlagEnvironment", b =>
                {
                    b.Navigation("FeatureFlagSegments");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.FlagsProject", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("FeatureFlags");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");

                    b.Navigation("SegmentGroups");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.ProjectEnvironment", b =>
                {
                    b.Navigation("FeatureFlagEnvironments");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.SegmentGroup", b =>
                {
                    b.Navigation("FeatureFlagSegments");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Switchly.WebApi.Entities.User", b =>
                {
                    b.Navigation("OrganizationMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
